version: '2.1'
volumes:
  db:

services:
  db:
    image: mysql/mysql-server:latest
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=dbrootpass
      - MYSQL_PASSWORD=dbuserpass
      - MYSQL_DATABASE=bigdata
      - MYSQL_USER=dbuser
    ports:
      - 3306:3306
    #command: ALTER USER 'dbuser' IDENTIFIED WITH mysql_native_password BY 'dbuserpass';